formats: ["json-schema"]
rules:
  property-snake-case:
    description: Property names should match snake case
    message: "{{path}} does not match snake case"
    given: $..properties.*~
    severity: error
    then:
      function: pattern
      functionOptions:
        match: '^[a-z]+[a-z0-9_]*[a-z0-9]+$'

  property-description:
    description: Every property should define a description
    message: "{{path}} does not define description"
    given: $..properties[?(@.type == 'string' || @.type == 'integer' || @.type == 'number' || @.type == 'boolean')]
    severity: error
    then:
      field: description
      function: truthy

  property-example:
    description: Every property should define an example
    message: "{{path}} does not define an example"
    given: $..properties[?(@.type == 'string' || @.type == 'integer' || @.type == 'number')]
    severity: error
    then:
      field: example
      function: truthy

# TODO: remove these exceptions as we clean up the schema and clarify  in RHCLOUD-8147
except:
  'schemas/system_profile/v1.yaml#/$defs/DiskDevice/properties/label': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/DiskDevice/properties/options/properties/name': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/DiskDevice/properties/options/properties/value': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/NetworkInterface/properties/mtu': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/YumRepo/properties/id': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/YumRepo/properties/name': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/YumRepo/properties/gpgcheck': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/YumRepo/properties/enabled': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/YumRepo/properties/baseurl': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/DnfModule/properties/name': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/DnfModule/properties/stream': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/InstalledProduct/properties/name': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/number_of_cpus': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/number_of_sockets': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/cores_per_socket': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/system_memory_bytes': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/infrastructure_type': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/infrastructure_vendor': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/bios_vendor': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/bios_version': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/bios_release_date': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/os_release': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/os_kernel_version': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/arch': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/last_boot_time': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/subscription_status': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/subscription_auto_attach': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/katello_agent_running': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/satellite_managed': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/cloud_provider': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/insights_client_version': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/insights_egg_version': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/captured_date': ['property-example', 'property-description']


