formats: ["json-schema"]
rules:
  property-snake-case:
    description: Property names should match snake case
    message: "{{path}} does not match snake case"
    given: $..properties.*~
    severity: error
    then:
      function: pattern
      functionOptions:
        match: '^[a-z]+[a-z0-9_]*[a-z0-9]+$'

  property-description:
    description: Every non-array type should define a description
    message: "{{path}} does not define description"
    given: $..[?((@property=='items' || @parentProperty=='properties') && @.type != 'array')]
    severity: error
    then:
      field: description
      function: truthy

  property-example:
    description: Scalar types (except for boolean) should define an example
    message: "{{path}} does not define an example"
    given: $..[?((@property=='items' || @parentProperty=='properties') && @.type != 'array' && @.type != 'object' && @.type != 'boolean' && @.type != null)]
    severity: error
    then:
      field: example
      function: truthy

  property-string-max-length:
    description: Every string type should define a max length
    message: "{{path}} does not define max length"
    given: $..[?((@property=='items' || @parentProperty=='properties') && @.type == 'string')]
    severity: error
    then:
      field: maxLength
      function: truthy

  property-field-sentence:
    description: Description of a field should be a sentence
    message: "{{path}} is not a sentence"
    given: $..[?(@property=='description')]
    severity: error
    then:
      function: pattern
      functionOptions:
        match: '^[A-Z]+\S*(?:\s+\S+){2,}\s*$'

  property-arbitrary-object-without-keys:
    description: Every object should have defined keys
    message: "{{path}} is an object without defined keys"
    given: $..[?(@.type == 'object')]
    severity: error
    then:
      field: properties
      function: truthy

# TODO: remove these exceptions as we clean up the schema and clarify  in RHCLOUD-8147
except:
  'schemas/system_profile/v1.yaml#/$defs/DiskDevice/properties/device': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/DiskDevice/properties/label': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/DiskDevice/properties/options/properties/name': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/DiskDevice/properties/options/properties/value': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/NetworkInterface/properties/mtu': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/YumRepo/properties/id': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/YumRepo/properties/name': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/YumRepo/properties/gpgcheck': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/YumRepo/properties/enabled': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/YumRepo/properties/base_url': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/DnfModule/properties/name': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/DnfModule/properties/stream': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/InstalledProduct/properties/name': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/NetworkInterface/properties/ipv4_addresses/items': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/NetworkInterface/properties/ipv6_addresses/items': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/cpu_flags/items': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/kernel_modules/items': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/running_processes/items': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/installed_services/items': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/enabled_services/items': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/number_of_cpus': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/number_of_sockets': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/cores_per_socket': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/system_memory_bytes': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/infrastructure_type': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/infrastructure_vendor': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/bios_vendor': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/bios_version': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/bios_release_date': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/os_release': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/os_kernel_version': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/arch': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/last_boot_time': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/subscription_status': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/subscription_auto_attach': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/katello_agent_running': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/satellite_managed': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/cloud_provider': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/insights_client_version': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/insights_egg_version': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/SystemProfile/properties/captured_date': ['property-example', 'property-description']
  'schemas/system_profile/v1.yaml#/$defs/NestedObject': ['property-arbitrary-object-without-keys']
  'schemas/system_profile/v1.yaml#/$defs/DiskDevice/properties/options': ['property-arbitrary-object-without-keys']
  'schemas/system_profile/v1.yaml#/$defs/NetworkInterface/properties/ipv4_addresses/items': ['property-string-max-length']
  'schemas/system_profile/v1.yaml#/$defs/NetworkInterface/properties/ipv6_addresses/items': ['property-string-max-length']
